# Based on
# https://github.com/schwankner/esa-snap-with-python/blob/master/Dockerfile
# but with Python 3.7
FROM up42-esa-snap:latest

ARG LIBS_DIR=blocks/snap-polarimetric/libs

RUN export DEBIAN_FRONTEND=noninteractive \
    && echo "deb [trusted=yes] http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list \
    && echo "deb-src [trusted=yes] http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends -t sid python3.7 python3-setuptools python3-pip build-essential ca-certificates python3-wheel python3-dev openjdk-8-jre-headless openjdk-8-jdk-headless

# Making sure JRE is installed before we jump into installing JDK.
#RUN apt-get install -y --no-install-recommends -t sid

RUN mkdir -p /interstellar/libs

COPY $LIBS_DIR/requirements.txt /interstellar/libs/
COPY $LIBS_DIR/setup.py /interstellar/libs/
WORKDIR /interstellar/libs
RUN pip3 install -r requirements.txt

RUN python3 setup.py install
