# Use debian stable as the base image.
FROM debian:stable

# Build argument defining the maximum heap size for gpt.
ARG MAX_HEAP_SIZE=4G

## Install wget.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get update -y \
&& apt-get --no-install-recommends install -y wget

# Get & setup the SNAP toolbox. Maximum heap size is set to 4GB.
RUN wget http://step.esa.int/downloads/7.0/installers/esa-snap_sentinel_unix_7_0.sh \
&& chmod 700 esa-snap_sentinel_unix_7_0.sh \
&& ./esa-snap_sentinel_unix_7_0.sh -q \
&& ln -s /usr/local/snap/bin/gpt /usr/bin/gpt \
&& sed -i -e "s/-Xmx1G/-Xmx${MAX_HEAP_SIZE}/g" /usr/local/snap/bin/gpt.vmoptions
